import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :quizir, QuizirWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# In production with a reverse proxy, SSL/HTTPS is terminated upstream.
# The container communicates strictly over plain HTTP.
# FORCE_SSL is false by default to prevent any redirect loops between the reverse proxy and container.
# If you want Phoenix to enforce SSL redirection, set FORCE_SSL=true.
force_ssl =
  if System.get_env("FORCE_SSL") in ~w(true 1 TRUE yes YES) do
    [
      rewrite_on: [:x_forwarded_proto],
      exclude: [
        # paths: ["/health"],
        hosts: ["localhost", "127.0.0.1", "app", "quizir"]
      ]
    ]
  else
    false
  end

config :quizir, QuizirWeb.Endpoint, force_ssl: force_ssl

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
